### ISSUE TITLE
Error trying to install obs-websocket-js on OS X

### ISSUE THREAD

**Issue by floriopics** [haganbmj/obs-websocket-js#104]
Trying to install the obs-websocket-js I'm getting an error on the Mac OS X:

sudo npm install obs-websocket-js --save
npm WARN node-sample@1.0.0 No description
npm WARN node-sample@1.0.0 No repository field.

+ obs-websocket-js@0.6.1
updated 1 package in 2.286s
[!] 1 vulnerability found [9 packages audited]
    Severity: 1 High
    Run `npm audit` for more detail

net-v501-00142:node-sample florio$ npm audit

sudo npm audit
                                                                                
                       === npm audit security report ===                        
                                                                                
# Run  npm install obs-websocket-js@1.2.0  to resolve 1 vulnerability
SEMVER WARNING: Recommended action is a potentially breaking change
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Denial of Service                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ ws                                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ obs-websocket-js                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ obs-websocket-js > ws                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/550                       │
└───────────────┴──────────────────────────────────────────────────────────────┘

[!] 1 vulnerability found - Packages audited: 9 (0 dev, 0 optional)
    Severity: 1 High

Any ideas on how to fix this?

### Versions Used (if applicable):
  - obs-websocket-js version:
  - obs-websocket plugin version:
  - obs-studio version:
  - node version:

**Comment by floriopics** [comment]
Ok running this solved it. 

npm install obs-websocket-js@1.2.0

**Comment by haganbmj** [comment]
Oh right, the new build of npm adds `audit`, I'll have a take a look at that. Off the top of my head I think `ws@3.2.x` was vulnerable to that and got patched. 
You should be alright to update from `obs-websocket-js@0.6.1` to `1.2.0` without too much pain, it's been a while though since `0.6.1` was back in June 2017 - If you run into any issues lemme know.
