### ISSUE TITLE
Make error messages consistent

### ISSUE THREAD

**Issue by dominik-korsa** [haganbmj/obs-websocket-js#119]
### Description:

Currently, errors in the plugins are inconsistent. For instance, when OBS is disabled and you use `obs.connect()` you get a WebSocket event with `type: "error"` field. It also throws `WebSocket connection to 'ws://localhost:4444/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED` which can't be caught using promise **onRejected** or `obs.on('error')`.

Incorrect password gives `{error: "Authentication Failed.", message-id: "2", status: "error", messageId: "2"}` - standard JS object, with different format.

Could you do something to make it consistent across the library?
Or at least a way to know which type it is, like a wrapper object for example?

### Versions Used:
  - obs-websocket-js version: 1.2.0
  - obs-websocket plugin version: 4.4.0
  - obs-studio version: 21.1.0 (64bit)
  - node version: 10.9.0

**Comment by haganbmj** [comment]
Sure, that makes sense to me. The `{error: '', status: ''}` responses are from obs-websocket directly, so I have some custom responses for some known error cases. Went ahead and just wrapped up the initial connection error as one of those.
Take a look at #120 and see if that would be sufficient to you. I'm pretty sure I'd want to append the original websocket error to that response object, but not entirely sure.

**Comment by dominik-korsa** [comment]
That's great! And quite fast actually :) Also I think the websocket error should be added, but do what you want :)

**Comment by haganbmj** [comment]
Yeah, sure thing. I'll see what I can do to wrap up the original error in that object.
When I was trying last night it didn't look like the error object was getting assigned with all of its fields...

I'll merge that tonight and tag a new release.

**Comment by haganbmj** [comment]
Just tagged a `1.3.0` release with that in it.
