### ISSUE TITLE
[Protocol] Rewrite with Versioning obs-websocket in Mind

### ISSUE THREAD

**Issue by haganbmj** [haganbmj/obs-websocket-js#12]
#### General Description:
- Working with the expectation that  [Palakis/obs-websocket](https://github.com/Palakis/obs-websocket) will be pushing new endpoints and likely changing old endpoints, it makes sense to implement some sort of version management now.
- Proposed method will be to maintain an API definition in the file, with each release of obs-websocket explicitly defined by RequestType, params, and response object.
- Add error handles, likely with Throw since not every request is required to pass a resolution callback/Promise-style argument... Though that would probably be better/more consistent to enforce that now.

**Comment by Palakis** [comment]
Currently, the numbering scheme I use is :

**Comment by Palakis** [comment]
Currently, the numbering scheme I'm thinking of for obs-websocket is :
MAJOR.MINOR.BUGFIX

which means : 
- MAJOR : Increments when **not** backwards-compatible protocol changes (existing commands updated) are implemented 
- MINOR : Increments when backwards-compatible protocol changes (new commands) and/or GUI changes are implemented
- BUGFIX : Increments when backwards-compatible bugs are fixed

**Comment by haganbmj** [comment]
Semantic. Yep that works. I'll be doing something similar. 
I've got this mostly written, just been busy. I'll just maintain a version lookup that identifies supported endpoints and naming changes then loads the version based on whatever GetVersion returns from obs-websocket.

**Comment by haganbmj** [comment]
If I can make a comment though, the issue I'm going to run into is that I need the web socket version bumped in advance of a release for people on development builds. 

Right now 0.3.2 is the release, but it's also the development version that contains changes for 0.4.0 or whatever is next. 

Ideally after each web socket release the very next commit should increment the version to x.y.z or x.y.z-alpha or something of the sort.

**Comment by Palakis** [comment]
Thought of it today. Gonna change this now!
