### ISSUE TITLE
SetTextFreetype2Properties - invalid request type

### ISSUE THREAD

**Issue by greenham** [haganbmj/obs-websocket-js#123]
### Description:
SetTextFreetype2Properties does not work, and fails with `'invalid request type'` on attempting to use it.
The error occurs with or without passed params. GetVersion indicates the request is available, however.

### Reproduction:
```
obs.setTextFreetype2Properties({})
	.then((x) => {
	    console.log('Success', x)
	})
	.catch((x) => {
	    console.log('Error', x)
	})
```

Sending these arguments fails as well:
```
{ source: 'now-showing-txt',
  'scene-name': 'test',
  render: true,
  text: 'test' }
```

```
Error { error: 'invalid request type',
  'message-id': '3',
  status: 'error',
  messageId: '3' }
```
### Versions:
* obs-websocket-js version: 1.2.0
* obs-websocket plugin version: 4.4.0
* obs-studio version: 22.0.2

### GetVersion Output:
```
{ 'available-requests': 'Authenticate,DisableStudioMode,EnableStudioMode,GetAuthRequired,GetBrowserSourceProperties,GetCurrentProfile,GetCurrentScene,GetCurrentSceneCollection,GetCurrentTransition,GetFilenameFormatting,GetMute,GetPreviewScene,GetRecordingFolder,GetSceneItemProperties,GetSceneList,GetSourceSettings,GetSourcesList,GetSourceTypesList,GetSpecialSources,GetStreamingStatus,GetStreamSettings,GetStudioModeStatus,GetSyncOffset,GetTextGDIPlusProperties,GetTransitionDuration,GetTransitionList,GetVersion,GetVolume,ListProfiles,ListSceneCollections,ResetSceneItem,SaveReplayBuffer,SaveStreamSettings,SetBrowserSourceProperties,SetCurrentProfile,SetCurrentScene,SetCurrentSceneCollection,SetCurrentTransition,SetFilenameFormatting,SetHeartbeat,SetMute,SetPreviewScene,SetRecordingFolder,SetSceneItemCrop,SetSceneItemPosition,SetSceneItemProperties,SetSceneItemRender,SetSceneItemTransform,SetSourceRender,SetSourceSettings,SetStreamSettings,SetSyncOffset,SetTextFreetype2Properties,SetTextGDIPlusProperties,SetTransitionDuration,SetVolume,StartRecording,StartReplayBuffer,StartStopRecording,StartStopReplayBuffer,StartStopStreaming,StartStreaming,StopRecording,StopReplayBuffer,StopStreaming,ToggleMute,ToggleStudioMode,TransitionToProgram',
  'message-id': '2',
  'obs-studio-version': '22.0.2',
  'obs-websocket-version': '4.4.0',
  status: 'ok',
  availableRequests: 'Authenticate,DisableStudioMode,EnableStudioMode,GetAuthRequired,GetBrowserSourceProperties,GetCurrentProfile,GetCurrentScene,GetCurrentSceneCollection,GetCurrentTransition,GetFilenameFormatting,GetMute,GetPreviewScene,GetRecordingFolder,GetSceneItemProperties,GetSceneList,GetSourceSettings,GetSourcesList,GetSourceTypesList,GetSpecialSources,GetStreamingStatus,GetStreamSettings,GetStudioModeStatus,GetSyncOffset,GetTextGDIPlusProperties,GetTransitionDuration,GetTransitionList,GetVersion,GetVolume,ListProfiles,ListSceneCollections,ResetSceneItem,SaveReplayBuffer,SaveStreamSettings,SetBrowserSourceProperties,SetCurrentProfile,SetCurrentScene,SetCurrentSceneCollection,SetCurrentTransition,SetFilenameFormatting,SetHeartbeat,SetMute,SetPreviewScene,SetRecordingFolder,SetSceneItemCrop,SetSceneItemPosition,SetSceneItemProperties,SetSceneItemRender,SetSceneItemTransform,SetSourceRender,SetSourceSettings,SetStreamSettings,SetSyncOffset,SetTextFreetype2Properties,SetTextGDIPlusProperties,SetTransitionDuration,SetVolume,StartRecording,StartReplayBuffer,StartStopRecording,StartStopReplayBuffer,StartStopStreaming,StartStreaming,StopRecording,StopReplayBuffer,StopStreaming,ToggleMute,ToggleStudioMode,TransitionToProgram',
  messageId: '2',
  obsStudioVersion: '22.0.2',
  obsWebsocketVersion: '4.4.0' }
```

**Comment by haganbmj** [comment]
Hm, you're getting an error from the obs-websocket plugin at least.
I was able to verify that calling `obs.setTextFreetype2Properties({})` sets the right request type.

```
{
  "message-id": "6",
​  "request-type": "SetTextFreetype2Properties",
  ...
}
```

but what I'm struggling to find is where in the 4.4.0 codebase that query is in the plugin... and why it shows up under `GetVersion`.
It doesn't show up in the generated docs and I can't find it at all at that tag's commit sha. It's even showing up on my current 4.3.3 installation's `GetVersion` despite not being a valid method.
https://github.com/Palakis/obs-websocket/tree/4e6d4ac437726b53e9d8734fa5f6e7850812fe1d

It looks like the method isn't in a stable release. There's a fairly large rewrite going on with the plugin, so I think it's delayed as part of that. I'll see if I can figure out why it shows up though.

**Comment by greenham** [comment]
Sounds good, thanks for the quick response!

**Comment by haganbmj** [comment]
So, the issue I have right now is that the plugin rewrite has a fairly large number of changes and I haven't been attentive to it.
I believe there's a slightly different authentication process, so I'll probably need to make some adjustments here to get that working.

I'll take a look at the rewrite and verify whether that's the case.

As for why `SetTextFreetype2Properties` is showing up in `GetVersion`, I have no idea so I opened up https://github.com/Palakis/obs-websocket/issues/253 to see if Palakis has any ideas.

**Comment by Lange** [comment]
The issue that @haganbmj linked in his previous comment has been closed, so I think this issue is also safe to close. Please post a comment and @-mention one of the maintainers in it if this is still an issue 🤠
