### ISSUE TITLE
Args are not optional when using a Callback.

### ISSUE THREAD

**Issue by BarryCarlyon** [haganbmj/obs-websocket-js#131]
### Description:

This does not work

```
obs.send('GetSpecialSources', function(e, d) {
    if (e) {
        console.log(e);
    } else {
        console.log('Special', d);
    }
})
```

This does work

```
obs.send('GetSpecialSources', {}, function(e, d) {
    if (e) {
        console.log(e);
    } else {
        console.log('Special', d);
    }
})
```

I added some weird logging™ to OBSWebSocket.js

And observed that the callback function was attempted to be stringified and passed to OBS over the socket…

You cannot have a callback, and have the arguments be optional.

### Versions Used (if applicable):
  - obs-websocket-js version: 2.0.1
  - obs-websocket plugin version: 4.4.0 (and tested with 4.5.0
  - obs-studio version: 22.0.2
  - node version: 10.14.2

**Comment by haganbmj** [comment]
Sure that's how multiple params work. I suppose I could look at the 2nd param type and make some determination on that.
You should be fine to pass undefined if you really don't want to compose an empty object.

**Comment by BarryCarlyon** [comment]
Usually in nodeJS/javascript you can do

```
function(callback() {});
```

```
function(args, callback() {});
```

or

```
function(foo, args, callback() {});
```

or

```
function(foo, callback() {});
```

And `function` checks whats passed to it to determine if whats passed is what it expects. So if args is optional, then I just do

```
function(thing, callback() {});
```

**Comment by Lange** [comment]
@BarryCarlyon I'm considering removing the callback API entirely, given that this library also supports Promises. Would you have any objections to this change?

**Comment by BarryCarlyon** [comment]
I'd have to check my code and see what I'm using.

I believe I'm primarily using callbacks so it would be a breaking change for me.

Not a problem but it does reduce user choice/flexibility.

**Comment by Lange** [comment]
https://github.com/haganbmj/obs-websocket-js/pull/142 would both retain the callbacks and make the `args` object optional. How does this look to you @BarryCarlyon?

**Comment by BarryCarlyon** [comment]
Seems good to me!
