### ISSUE TITLE
OBSWebSocket is not a constructor error 

### ISSUE THREAD

**Issue by RubyComputer** [haganbmj/obs-websocket-js#17]
#### Type of Issue:
- e.g. Bug / Enhancement / Suggestion / Development Trouble
bug

#### General Description:
- Details.
OBSWebSocket is not a constructor error when using code.

**Comment by RubyComputer** [comment]
fixed! :)

By using var OBSWebSocket = require('obs-websocket-js')**.OBSWebSocket**;

Documentation suggested a different way. 

gg

**Comment by haganbmj** [comment]
Yeah whoops. I don't node good.
