### ISSUE TITLE
Offering to help as contributor

### ISSUE THREAD

**Issue by Lange** [haganbmj/obs-websocket-js#18]
Hi @haganbmj!

I noticed you said that you don't have as much time as you'd like to dedicate to the obs-websocket-js project. I'd be happy to help with some of the code work if you could clearly lay out a list of tasks on the [project board](https://github.com/haganbmj/obs-websocket-js/projects). This would help me know where to start and let me work the fastest. Let me know if this organizational work is something you have time for.

Thanks,
Alex

**Comment by haganbmj** [comment]
Yeah certainly, I'll make up a couple more issues and organize a couple things.
I'd appreciate it.
