### ISSUE TITLE
implementation help

### ISSUE THREAD

**Issue by thewayur** [haganbmj/obs-websocket-js#180]
hi. i am sorry for stupid question.

how i would implement it in my html/js web app without going through node js?
i dont see any /dist folder and related obs-websocket.js

**Comment by Brendonovich** [comment]
You can download the web distributable from the Download link in the README, which links to [this file](https://raw.githubusercontent.com/haganbmj/obs-websocket-js/gh-pages/dist/obs-websocket.js).
