### ISSUE TITLE
Suggestion: Client rather than server

### ISSUE THREAD

**Issue by CloakedAlien** [haganbmj/obs-websocket-js#196]
Would it be possible to reverse the way this works? I.e. make OBS establish a connection to a server rather than the other way around? Communication protocol wouldn't need to be changed but it would make it easier to establish secure connections. 

Also if you think about it with Twitch and Bots it would make more sense if your OBS can connect to your 24/7-running bot without IP or port forwarding rules having to be dealt with all the time =)

**Comment by Lange** [comment]
While that may be a decent idea, it is out of the scope of this project.
