### ISSUE TITLE
[Build] Reduce Webpack Output File Size

### ISSUE THREAD

**Issue by haganbmj** [haganbmj/obs-websocket-js#23]
**General Description:**
There's a whole bunch of unneeded bloat being loaded in with `sha.js` and `url` especially.

**Comment by mikerhyssmith** [comment]
I'd be happy to take a look at this, not sure what approach you had in mind, but Id assume adding in tree shaking and minification etc into the webpack config ?

**Comment by haganbmj** [comment]
Yeah, definitely the tree shaking at least.  
I had an uglify plugin in grunt, but it doesn't seem to support some es6 functionality. Being that I'm not generating docs right now Grunt doesn't really have a purpose.  

There's just not much sense in letting this project be 135kb full of extra crpyto functionality.

**Comment by haganbmj** [comment]
Swapped over to webpack entirely, re-added a `.min` build which comes in right around 40kb.
It could certainly go smaller - still pulling in a lot of excess for sha256, but I'm content with that for the moment at least.
I'll likely end up just copying only the sha256 functions necessary directly into this project and removing the dependency.. Or look for a smaller package.
