### ISSUE TITLE
start / stop stream / record error

### ISSUE THREAD

**Issue by HagenMo** [haganbmj/obs-websocket-js#26]
Hi haganbmj,

at first: Thank you for this project! My first steps on controlling the obs websocket were quite positive. There is one thing, that doesn't work for me as expected:

I get an error on sending a 'StartStreaming', 'StopStreaming', 'StartRecording' or 'StopRecording' request:

> [OBSWebSocket] Error: invalid request type

I wrote the function myself based on the already existing and working 'StartStopStreaming' - request in obs-websocket.js:

`OBSWebSocket.prototype.startStreaming = function() {
    this._sendRequest('StartStreaming');
  };`

Here is my system:

- obs-websocket-js v0.3.3
- obs-websocket plugin v4.0.0
- obs v18.0.1

I worked with the [official websocket plugin protocol](https://github.com/Palakis/obs-websocket/blob/master/PROTOCOL.md) and couldn't see any complications concerning the [RequestHandler](https://github.com/Palakis/obs-websocket/blob/master/WSRequestHandler.cpp).

Do you know what causes this error and how to solve it?

Many thanks!

**Comment by Palakis** [comment]
@HagenMo You can't use these request types in 4.0.0. These are implemented for 4.1.

**Comment by HagenMo** [comment]
Ah, good to know! Many thanks!

**Comment by haganbmj** [comment]
Sounds right to me :) - thanks @Palakis
