### ISSUE TITLE
[Style] Consider using ESlint instead of jshint

### ISSUE THREAD

**Issue by Lange** [haganbmj/obs-websocket-js#27]
[ESlint](http://eslint.org/) is more common these days and has more active development. In addition, there are several widely used eslint configs, and you can easily add your own per-project preferences on top of these configs.

- [eslint-config-xo](https://github.com/sindresorhus/eslint-config-xo) - My personal favorite (I specifically use the `xo/esnext` variant for ES6), also available in a variant that uses [2 spaces instead of tabs](https://github.com/sindresorhus/eslint-config-xo-space)
- [eslint-config-airbnb](https://www.npmjs.com/package/eslint-config-airbnb) - Airbnb's config
- [eslint-config-standard](https://www.npmjs.com/package/eslint-config-standard) - Enforces JavaScript [Standard](https://standardjs.com/) style
- [eslint-config-eslint](https://www.npmjs.com/package/eslint-config-eslint) - The default eslint config
- [eslint-config-google](https://www.npmjs.com/package/eslint-config-google) - Google's config

Let me know if any of these seem good to you, and I'll open a PR to implement it.

**Comment by haganbmj** [comment]
Sure, whichever you're comfortable with would be fine. I would prefer to keep with using 2 spaces, though.
