### ISSUE TITLE
[Log] Silence logging by default

### ISSUE THREAD

**Issue by Lange** [haganbmj/obs-websocket-js#32]
Currently, obs-websocket-js is quite noisy in the console with its log messages. It's generally standard for libraries to be "silent" -- that is: to only print output to the console if the consumer of that library has explicitly requested this behavior via some type of debug flag, configuration parameter, or environment variable.

@haganbmj If it's okay with you, I'll open a PR that silences all log statements by default unless some debug flag has been set to true.

**Comment by Lange** [comment]
As part of this: the library also should generally not `catch` promise errors. In most cases, it's best to let the consumer decide how they wish to handle these.

**Comment by haganbmj** [comment]
Yeah of course, for some reason I have it setting the log level [here](https://github.com/haganbmj/obs-websocket-js/blob/master/lib/Socket.js#L7)
