### ISSUE TITLE
onSceneListChanged not working

### ISSUE THREAD

**Issue by Hardy535** [haganbmj/obs-websocket-js#5]
I don't know if I'm doing it wrong but using the callback onSceneListChanged doesn't work for me.
The response I get from this function is always _null_.

For example this gives me _null_:
`ws.onSceneListChanged = function(response) {
	console.log(response);
};`

I got no problem with other functions like 'onSceneSwitch' for example.

**Comment by haganbmj** [comment]
Sorry about that, forgot to update the method at some point.
Should work as intended now.

As a note though, the SceneListChanged event doesn't seem to get triggered by deleting or rearranging scenes.
I believe that would be an issue with obs' frontend api, I'll double check at some point and see, but it's certainly not something I can correct in this project.
