### ISSUE TITLE
[API] Use async/await

### ISSUE THREAD

**Issue by haganbmj** [haganbmj/obs-websocket-js#53]
Update `.send` to async/await assuming there's webpack support for it.

**Comment by Kaliph** [comment]
Is this something you still need testers for? I would like to use async/await with your library.

**Comment by haganbmj** [comment]
You already can, something like the following would be fine as either returns a promise.

`const resp = await obs.send('GetCurrentScene')`
`const resp = await obs.getCurrentScene()`
