### ISSUE TITLE
scene names with "special" characters don't work

### ISSUE THREAD

**Issue by Hardy535** [haganbmj/obs-websocket-js#6]
Scene names in OBS with characters like "Ä", "Ü", "Ö", "ß" (pretty important for germans) don't work.
There's an error when trying to send the scene name to OBS (needed for 'setCurrentScene').

**Comment by haganbmj** [comment]
Fairly sure that's an issue with obs-websocket, I'll have to look into it a bit more.

The characters get there, they just aren't handled correctly

`[obs-websockets] invalid JSON payload for '{"scene-name":"Änd","message-id":"11","request-type":"SetCurrentScene"}'`

**Comment by haganbmj** [comment]
Issue https://github.com/Palakis/obs-websocket/issues/28 has been closed.

This requires no additional changes from this end, so you'll see this resolved once you consume the latest obs-websocket.dll (whenever the next release of that is).
