### ISSUE TITLE
SetTextGDIPlusProperties - invalid request type

### ISSUE THREAD

**Issue by ConnorMcF** [haganbmj/obs-websocket-js#62]
### Description:
SetTextGDIPlusProperties does not work, and fails with `'invalid request type'` on attemping to use it.
The error occurs with or without passed params.

### Reproduction:
```
obs.setTextGDIPlusProperties({})
	.then((x) => {
	    console.log('Success', x)
	})
	.catch((x) => {
	    console.log('Error', x)
	})
```
```
Error { error: 'invalid request type',
  'message-id': '2',
  status: 'error',
  messageId: '2' }
```

### Versions:
  - obs-websocket-js version: 0.7.0
  - obs-websocket plugin version: 4.0.0
  - obs-studio version: 19.0.3

**Comment by haganbmj** [comment]
SetTextGDIPlusProperties wasn't implemented on the plugin side until 4.1.0, so try with that version of the plugin.
https://github.com/Palakis/obs-websocket/releases/tag/4.1.0

**Comment by ConnorMcF** [comment]
Updated obs-websocket and everything's working fine.
Cheers!

**Comment by haganbmj** [comment]
Awesome, glad that worked.
