### ISSUE TITLE
async connect Unexpected identifier

### ISSUE THREAD

**Issue by Kaliph** [haganbmj/obs-websocket-js#66]
This is a Bug report I am trying to run obs-websocket-js in my node.js app.
when the script tries to connect I get following errormessage. Any help would be appreciated.

> C:\project\scheduler-windows\node_modules\obs-websocket-js\lib\Socket.js:36
  async connect(args = {}, callback) {
        ^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\project\scheduler-windows\node_modules\obs-websocket-js\lib\OBSWebSocket.js:1:78)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)<!--

### Steps to Reproduce the Issue (if applicable):
  1. Install all Tools copy code below to a js file and start node.js 
  2. ...  
  3. ...  

### Versions Used (if applicable):
  - obs-websocket-js version: 0.7.0
  - obs-websocket plugin version: 4.0
  - obs-studio version: 20.0.1

### This is my Node.js code and I want to connect to localhost:4444
...
`const OBSWebSocket = require('obs-websocket-js');
const obs = new OBSWebSocket();

// Declare some events to listen for.
obs.onConnectionOpened(() => {
  console.log('Connection Opened');

  // Send some requests.
  obs.getSceneList({}, (err, data) => {
    console.log("Using callbacks:", err, data);
  });

  obs.getSceneList().then(data => {
    console.log("Using promises:", data);
  });
});

obs.onSwitchScenes(data => {
  console.log(data);
});

obs.connect();`

**Comment by haganbmj** [comment]
What node version are you using?
I don't think async was made standard until node 7.6 or something.

I think you can run on 7.5 or something with `node whatever.js --harmony`?

**Comment by Kaliph** [comment]
Thankyou. Node 8.4 solved this issue. Thankyou for this hint!

**Comment by haganbmj** [comment]
Updated the project to hopefully ensure this doesn't happen in the future if people want to use older versions of node.
Try updating to obs-websocket-js `v0.8.0` if you want to go back to an older node version and let me know if you run into any issues.

**Comment by Kaliph** [comment]
Ok. This is good news. Was already wondering how people on older node.js versions get this to work..
That said does that mean I can't run newer versions of obs-websocket-js with node.js 6.9 e.g. ?


Am 23.08.17 um 23:09 schrieb Brendan Hagan

**Comment by haganbmj** [comment]
Should work with any version of node > 4.
Tests are run with Node 4.8.4 and I've been working with Node 8.1.2.
