### ISSUE TITLE
Syntax  Error unexpected identifier

### ISSUE THREAD

**Issue by Kaliph** [haganbmj/obs-websocket-js#67]
### Description:
When trying to send a command to obs websocket. I get following error. I think my syntax is somehow not ok. But I am not too much into Promises right now. Can u help me? Also it would be nice if u could bring some light on the args that are supported. How does a typical args look like?

### Steps to Reproduce the Issue (if applicable):
  1. Install packages and copy code below into a function and execute it.
  2. ...  
  3. ...  

### Versions Used (if applicable):
  - obs-websocket-js version: 0.7.0
  - obs-websocket plugin version: 4.0.0
  - obs-studio version: 20.0.1
  - node.js 8.5

### Extra Information / Code Samples / etc:
`C:\project\startstop\modules\obs.js:36
    obs.send('StartRecording', {args}, callback(err, data)) returns Promise
                                                            ^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:537:28)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\project\startstop\modules\socketio.js:3:11)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)`

**Comment by Kaliph** [comment]
I have now figured out that the first command works and sends data back. If I want to Set something I get an error saying UnhandledPromiseRejectionWarning

`obs.GetPreviewScene().then(data => {
  console.log(data);
});`

`obs.SetCurrentProfile('blumen').then(data => {
  console.log(data);
});`

With this command I want to load profile 'blumen'

**Comment by haganbmj** [comment]
Promises are a way to allow something to happen later, out of order.

So in your sample there you'd want something like

```js
obs.send('StartRecording', {})
      .then(function(data) {
            // StartRecording doesn't return any information, but now we know that obswebsocket acknowledged and performed it.
     })
     .catch(function(error) {
            // If there was some kind of error, such as you not being authenticated then this would happen.
    });
```

`async/await` are kind of the next generation of promises though. Rather than having to use `then` and `catch` you get the option to write more normal looking code.

```
try {
    let data = await obs.send('StartRecording', {});
    // data would be empty, but the above "waits" until it gets a response.
} catch (error) {
    // Again, this would probably be not authenticated.
}
```

**Comment by haganbmj** [comment]
Also it looks like you were sending `{args}`,
Just want to make sure you recognize that those are what are defined in https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#setcurrentscene

So for SetCurrentScene I'd need something like this

```js
obs.send('SetCurrentScene' { 'scene-name': 'scene1' });
```

**Comment by Kaliph** [comment]
Thankyou for your help. 

Gesendet mit der GMX iPhone App

Am 18.08.17 um 16:53 schrieb Brendan Hagan
