### ISSUE TITLE
setSourceVisbility not working

### ISSUE THREAD

**Issue by Hardy535** [haganbmj/obs-websocket-js#7]
Using 'setSourceVisbility' always gives me the error `[OBSWebSocket] Error: invalid request type`.

Example code:
`ws.setSourceVisbility("Gamerecording", false);`

Am I doing it wrong or is it a bug?

**Comment by haganbmj** [comment]
No, you're doing it 100% correctly. I'm just an idiot and was sending the wrong request type.
