### ISSUE TITLE
Provide better documentation for API?

### ISSUE THREAD

**Issue by darranhall** [haganbmj/obs-websocket-js#74]
I can't seem to, no matter how hard I dig inside of the files, find what data I need to send to the websocket. Such as the parameters to record (what do I even send with it?). Can we get some documentation?

**Comment by darranhall** [comment]
Nevermind, after a little more looking around, I did manage to find the solutions in the original websocket source. Mark this issue as closed, I'm so embarassed.

**Comment by haganbmj** [comment]
No worries, I'll update the readme to have a prominent link to that.
https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md
