### ISSUE TITLE
Switch to Scene Hotkeys doesn't update .onPreviewSceneChanged()

### ISSUE THREAD

**Issue by MasterDalK** [haganbmj/obs-websocket-js#79]
### Description:
Use of assignable keyboard hotkeys in the OBS Settings to "Switch to Scene" don't seem to give a response for the function .onPreviewSceneChanged(). Clicking to a scene does provide a response however.

We use a multiview application we've created that connects to obs-websocket via the JS to light up previewed scenes/sources green, and live as red. The console output of this application shows no updates when using hotkeys to pick a previewed scene, however does when clicking or using a hotkey/clicking to push the scene live.

### Versions Used:
  - obs-websocket-js version: 0.9.0
  - obs-websocket plugin version: 4.1.0
  - obs-studio version: 20.0.1

I wasn't sure if this was a obs-websocket or obs-websocket-js issue so I've created the issue for -js for now.

**Comment by haganbmj** [comment]
Ah, that sounds like it might be an OBS api issue.

The obs-websocket plugin just listens for "PreviewSceneChange" and this -js project listens to that by proxy. 
There's a bit of hacky logic over in the plugin around studio mode (see https://github.com/Palakis/obs-websocket/issues/72), I can see if Palakis knows anything about that.

If OBS itself isn't sending out that update then there's really no way to pick it up at this stage, though.

(I went ahead and logged https://github.com/Palakis/obs-websocket/issues/127 to see if Palakis knows anything.)

**Comment by Lange** [comment]
I'm closing this here since it seems to be an upstream issue in `obs-websocket`, as linked in the previous comment.
