### ISSUE TITLE
Disconnect function

### ISSUE THREAD

**Issue by Hardy535** [haganbmj/obs-websocket-js#8]
Something like a disconnect function from the websocket would be helpful to correctly close a connection.
Maybe this will prevent OBS from crashing when trying to connect multiple times (just an idea).

**Comment by haganbmj** [comment]
Sorry for the delay, was out with the flu for a week.
Yep a disconnect function (among the other changes you mentioned) would be good. That said, I need to basically rewrite everything here. It was a quick copy from what I thought people were using with the previous obs-remote and doesn't really serve any purpose when all it really needs to do is help with the the authentication encryption.

**Comment by Hardy535** [comment]
Great to hear that, really looking forward to new updates you make :)

**Comment by haganbmj** [comment]
Was planning to do some more of the refactor at the same time, but for now just the disconnect method is there - should've just pushed that when I wrote it 10 minutes after writing that last message >.>
