### ISSUE TITLE
How to connect to several instances same time?

### ISSUE THREAD

**Issue by Kaliph** [haganbmj/obs-websocket-js#85]
- I would like to connect to several Obs Studios with Websocket, running on the same machine.
  - This works from Webserver side by using --portable --multi as an option to the Link.

  - Start 2 Instances of ObsStudio 20.1.0. and obs-websocket 4.0.0

### Example

```
var obsstudio = [{"ipaddress": "127.0.0.1", "tcpport": "1111", "password": "1111"},{"ipaddress": "127.0.0.1", "tcpport": "2222", "password": "2222"}]; 
var data = obsstudio; 
var length = data.length; 
console.log("Numberof Obs STudios defined " + length);

var j = 0; 
for (; j < length;) {                
                var newdata = data[j];
                var ipaddress = newdata.ipaddress;
                var tcpport = newdata.tcpport;
                var password = newdata.password;
                var address = ipaddress + ":" + tcpport;

                console.log("OBS Studio data to connect " + address + " " + password);
                obs[j] = new OBSWebSocket();
                obs[j].connect({ address: address, password: password })
                .then((data) => {

                   console.log('Success! We\'re connected & authenticated with. ' + address);

                    obs[j].getSceneList({}).then(data => {
                        console.log("getSceneList ObsConnect: " + data);
                    });

                }).catch(err => { // Ensure that you add a catch handler to every Promise chain. 
                    logger.error("Connection Error " + err);
                });

            j++;
      };
```

This gives following Error.

Connection Error TypeError: Cannot read property 'getSceneList' of undefined

### Versions Used (if applicable):
  - obs-websocket-js version: 0.8.0
  - obs-websocket plugin version: 4.0.0
  - obs-studio version: 20.1.0
  - node version: 8.7.0

**Comment by haganbmj** [comment]
Sorry, missed that message.

Since you're using `j` to keep track of your index you're running into issues where `j` is changing value.

Essentially you're creating an `obs[0]` and `obs[1]`, which looks fine - when you try to call `.getSceneList`, however, it uses whatever `j` currently is - so in this case you're getting `obs[2]` which doesn't exist.

This has to do with scope and asynchronous behavior. The value of `j` is shared so it keeps changing. Connecting to OBS is asynchronous, so you're absolutely not guaranteed that the logic in your `.then()` statement will execute before `j` is changed to an invalid value.

**Comment by haganbmj** [comment]
Here's something real simple that would fix this current issue using your code, though I think you're going to be looking for something better in the future.

```
var obsstudio = [{"ipaddress": "127.0.0.1", "tcpport": "1111", "password": "1111"},{"ipaddress": "127.0.0.1", "tcpport": "2222", "password": "2222"}]; 
var data = obsstudio; 
var length = data.length; 
console.log("Numberof Obs STudios defined " + length);

var j = 0; 
for (; j < length;) {                
                var k = j; // Create a new variable within this for loop that will store whatever j is at this very moment regardless of what it changes to.
                var newdata = data[k];
                var ipaddress = newdata.ipaddress;
                var tcpport = newdata.tcpport;
                var password = newdata.password;
                var address = ipaddress + ":" + tcpport;

                console.log("OBS Studio data to connect " + address + " " + password);
                obs[k] = new OBSWebSocket();
                obs[k].connect({ address: address, password: password })
                .then((data) => {

                   console.log('Success! We\'re connected & authenticated with. ' + address);

                    obs[k].getSceneList({}).then(data => {
                        console.log("getSceneList ObsConnect: " + data);
                    });

                }).catch(err => { // Ensure that you add a catch handler to every Promise chain. 
                    logger.error("Connection Error " + err);
                });

            j++;
      };
```

**Comment by Kaliph** [comment]
Ok thankyou for your answer. I´ll give this a try. Just wondering if I will be able to differ between the 2 connections. 

```
const obs = new OBSWebSocket();
var obs = [];
```

Because first I say "obs = new OBSWebSocket();"
And then I assign "var obs = [];"

I think I will always get the SceneList of the Last Connected OBS Studio.
But I want to have 2 connected the same time and also send request the same time to 2 different OBS Studio instances.

**Comment by haganbmj** [comment]
You can't use the same variable name (`obs`) for both.

```
const obs = []; // Create an array.

obs[0] = new OBSWebSocket(); // Start to fill the array.
obs[1] = new OBSWebSocket();

obs[0].connect({ address: '127.0.0.1:1111', password: '1111' }); // Open up the connections.
obs[1].connect({ address: '127.0.0.1:2222', password: '2222' });
```

Now to interact  with these two separate connections you just need to specify which one.

**Comment by Kaliph** [comment]
Thankyou!! Thumbs up!!

**Comment by Kaliph** [comment]
I have only one issue left to control several Obs Studios. I have one function that connects 2 OBS Studios and I have one function that tries to switch a Scene on Obs Studio 1. But unfortunately obs[1] is not defined.
I know this is just a issue of variable declaration and scope, but at the moment I don´t know how to solve this. Would be great if u could show me what I am doing wrong. Thankyou

 `const OBSWebSocket = require('obs-websocket-js');
const obs = []; // Create an array.

function ObsConnect(data) {

obs[0] = new OBSWebSocket(); // Start to fill the array.
obs[1] = new OBSWebSocket();

obs[0].connect({ address: '127.0.0.1:1111', password: '1111' }).then(data => {
    obs[i].getSceneList().then(data => {
      console.log('OBS #' + i + ' scene list: ', data);
    });
  }).catch(err => {
    console.log('OBS #' + i + ' was unable to connect.', err);
  }); // Open up the connections.

obs[1].connect({ address: '127.0.0.1:2222', password: '2222' }).then(data => {
    obs[i].getSceneList().then(data => {
      console.log('OBS #' + i + ' scene list: ', data);
    });
  }).catch(err => {
    console.log('OBS #' + i + ' was unable to connect.', err);
  });;

};

function ObsSwitchScene(data) {

obs[1].SetCurrentScene({'scene-name':scenename}).then(data => {

	console.log("Scene switched");
});

};

Error: Cannot set SetCurrentScene of undefined`
