### ISSUE TITLE
Trim Readme

### ISSUE THREAD

**Issue by haganbmj** [haganbmj/obs-websocket-js#87]
Trim down the Readme to be more legible. There's a lot of fluff in there right now and some of the variable descriptions are like 2 lines long.

Should probably eliminate all suggestions of using PascalCase too.

**Comment by haganbmj** [comment]
Stress the recommended use of `obs.send('MethodName')` syntax as per #89

**Comment by Lange** [comment]
The README got trimmed down a good amount when the old bound method syntax was removed. I think it's alright now 👍
