### ISSUE TITLE
SetSceneItemProperties = "invalid request type"

### ISSUE THREAD

**Issue by illusdidi** [haganbmj/obs-websocket-js#88]
Hi, I got some trouble with the command SetSceneItemProperties :
`obs.SetSceneItemProperties({"scene-name": "AUX", "item": auxelem, "visible": false});`
On the chrome console I get :
 `Uncaught (in promise) {error: "missing request parameters", message-id: "6", status: "error", messageId: "6"}`
I think the json structure is fine.
Thank you.

### Versions Used (if applicable):
  - obs-websocket-js version: OBS WebSocket Javascript API (obs-websocket-js) v1.0.0 Build Timestamp: 2017-11-09 15:44:36+00:00
  - obs-websocket plugin version: 4.2.0
  - obs-studio version: 20.1.1

**Comment by haganbmj** [comment]
SetSceneItemProperties has a bunch of values. https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#setsceneitemproperties

If you just need visible I would do this until that gets simplified. 

 https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#setsourcerender

**Comment by haganbmj** [comment]
Actually, just reread the implementation and it should be fine to use.  

Make sure `item` is just the name of the source. You are using a variable (`auxelem`) in your example so I can't tell.

**Comment by illusdidi** [comment]
wow thank you for your quick response. I tried to replace the variable by the name like `'Scene1'` but the problem was the same. I'll use SetSourceRender then.

**Comment by illusdidi** [comment]
In fact I got  "invalid request type" not "missing request parameters" sorry.

**Comment by haganbmj** [comment]
Oh, `invalid request type`. I think `SetSceneItemProperties` is in 4.2.1, which hasn't gotten a release yet.
If you're on Windows you can download the latest build of obs-websocket here: https://ci.appveyor.com/project/Palakis/obs-websocket/build/refcount-refactor-439/artifacts

**Comment by haganbmj** [comment]
`invalid request type` means that the obs-websocket plugin doesn't know what `SetSceneItemProperties` is.

**Comment by illusdidi** [comment]
Yes I think you're right. Thank you very much for your help!
