### ISSUE TITLE
Determine how best to handle back compatibility for obs-websocket api changes

### ISSUE THREAD

**Issue by haganbmj** [haganbmj/obs-websocket-js#89]
### Description
This hasn't happened since some of the earliest versions I don't think, but there have been API endpoints removed/renamed on the obs-websocket plugin side in the past and with the potential for a large 5.0 rewrite on the horizon it's likely that this will happen again.

Being that this project binds methods at runtime based on the obs-websocket api docs, there's a good chance that this will fail to bind some method that consumers are looking for while would lead to some unclear and possibly inaccurate (depending on their plugin version) runtime exceptions.

Need a way to track the addition/removal of api endpoints. My gut says that that should just be accomplished by maintaining a list of methods from each obs-websocket version release and reducing that either dynamically or statically so that it can be more concisely bundled.

**Comment by haganbmj** [comment]
Ideally consumers would just call `obs.send('MethodName')` and it would be completely the plugin's responsibility to handle back compatibility, but I do like supporting bound methods and it's not super difficult to do so.

**Comment by Lange** [comment]
The base API now only provides `.send` and `.on` methods, and it is up to the consumer to provide accurate method and event name strings. The upcoming auto-generated typedefs will indeed be specific to a given version of `obs-websocket`, but I think it is reasonable for folks to simply ensure that their `obs-websocket` installation matches the typedef they are trying to use.
