### ISSUE TITLE
Issue and Request

### ISSUE THREAD

**Issue by MRVDOG** [haganbmj/obs-websocket-js#9]
Hi, my issue is, for some reason source bounds are `0`, I can't work out if this is a `obs-websocket-js` or a `obs-websocket` issue

![image](https://cloud.githubusercontent.com/assets/4422624/21951529/95ad2350-d9ff-11e6-8e47-b6dda4edd0f6.png)

my request is for more events/functions, for example, I want to be able to change a sources position and dimensions when, for example, I use jQueryUI `draggable()` and `resize()` to change them on my webUI

![image](https://cloud.githubusercontent.com/assets/4422624/21951492/31e51422-d9ff-11e6-8dcd-6941cf36a7c9.png) The WebUI so far, this is for a friend to be able to control his OBS when he's at conventions, etc...

I also posted this over at `obs-websocket`

**Comment by haganbmj** [comment]
I haven't been able to get a bounds value out of obs-websocket, I don't believe those values come out of obs-studio at all right now.

I'm not entirely sure on changing dimensions, I know at the moment obs-websocket doesn't support that. Palakis has a placeholder for that functionality, though, so it might be possible with the current obs-studio API and just hasn't been written.

**Comment by Palakis** [comment]
No, atm you can't move an item or change its size. However, I remember having implemented the ability to get the position and size of an item. Gonna check this out in the coming days.

**Comment by krazyken04** [comment]
Any progress on this? Was toying with an idea of a NodeCG using this to change a scene's sources / transforms on the fly and wanted to see how far I could push that. 

Specifically looking at these: 
- [SetSceneItemPosition](https://github.com/Palakis/obs-websocket/blob/master/PROTOCOL.md#setsceneitemposition) & [SetSceneItemTransform](https://github.com/Palakis/obs-websocket/blob/master/PROTOCOL.md#setsceneitemtransform)

**Comment by Palakis** [comment]
@krazyken04 the bounds issue is fixed in the current codebase. It will be included in the next release of obs-websocket. You can follow the development (and see if you can help) [here](https://github.com/Palakis/obs-websocket/projects/2).

**Comment by haganbmj** [comment]
I'm rewriting this.
I'll have Position/Transform in there, they're not currently in a 'released' version of obs-websocket. If you'd like to have the functionality now you can call the following methods, but I can't guarantee I'll keep this internal formatting for the next version.

```
ws._sendRequest('SetSceneItemPosition', { 'item': 'SOURCE_NAME', 'x': 123, 'y': 123 }, callback);
ws._sendRequest('SetSceneItemTransform', { 'item': 'SOURCE_NAME', 'x-scale': 2.5, 'y-scale': 2.5, 'rotation': 90 }, callback);
```

**Comment by haganbmj** [comment]
Rewrite was published. I'll be doing some documentation and stuff, but in the meantime read here for more info
Note that I pretty much abandoned all the custom method names and such.

https://github.com/haganbmj/obs-websocket-js/pull/16#issuecomment-296420115
